apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  selector:
    matchLabels:
      app: cicd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: 349495027745.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-app:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-app
spec:
  selector:
    app: cicd-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000